// Generated by CoffeeScript 1.4.0
(function() {
  var get_cover_pic, get_stats_html, root;

  root = typeof exports !== "undefined" && exports !== null ? exports : this;

  root.ddg_spice_facebook_fanpage = function(data) {
    var content, items;
    if (data.username) {
      items = [];
      items[0] = [];
      items[0]['h'] = "" + data.name + " - " + data.category;
      items[0]['s'] = "" + data.name + " on Facebook";
      items[0]['u'] = data.link;
      content = '';
      if (data.cover && data.description) {
        content = "" + content + "\n<div style=\"margin-top: 10px; margin-bottom: 5px;\">\n	" + (get_cover_pic(data)) + "\n	<div>\n		<div id=\"likes\" style=\"font-weight: bold;\">\n			" + (get_stats_html(data)) + "\n		</div>\n		<div>\n			" + data.description + "\n		</div>\n	</div>\n	<div style=\"float: clear;\"></div>\n</div>";
      } else if (data.cover) {
        content = "" + content + "\n<div style=\"margin-top: 10px; margin-bottom: 5px;\">\n	" + (get_cover_pic(data)) + "\n	<div style=\"margin-top: 10px; font-weight: bold;\">\n		" + (get_stats_html(data)) + "\n	</div>\n	<div style=\"float: clear;\"></div>\n</div>";
      } else if (data.description) {
        content = "<div style=\"margin-top: 10px; margin-bottom: 5px;\">\n	<div style=\"font-weight: bold;\">" + (get_stats_html(data)) + "</div>\n	<div style=\"margin-top: 5px;\">\n		" + data.description + "\n	</div>\n</div>";
      } else {
        content = "" + content + "\n<div id=\"likes\" style=\"margin-top: 10px; margin-bottom: 5px; font-weight: bold;\">\n	" + (get_stats_html(data)) + "\n</div>";
      }
      items[0]['a'] = content;
      return nra(items);
    }
  };

  get_cover_pic = function(data) {
    var content;
    content = "<div style=\"float: left; margin-right: 10px; margin-left: 5px;\">\n	<img style=\"height: 150px; width: 150px;\" src=\"" + data.cover.source + "\"></img>\n</div>";
    return content;
  };

  get_stats_html = function(data) {
    var content;
    content = "Talking About: " + (data.talking_about_count != null ? data.talking_about_count : 0) + ".\nFans: " + (data.likes != null ? data.likes : 0) + ".\nWere Here: " + (data.were_here_count != null ? data.were_here_count : data.were_here_count) + ".";
    return content;
  };

}).call(this);
