// Generated by CoffeeScript 1.4.0
var ddg_spice_xkcd;

ddg_spice_xkcd = function(xk) {
  var div, img, imgUrl, items, link, snippet;
  img = void 0;
  snippet = void 0;
  link = void 0;
  div = void 0;
  if (xk["img"] && xk["alt"]) {
    snippet = d.createElement("span");
    imgUrl = "/iu/?u=" + xk["img"];
    if (nur) {
      img = nur("", xk["alt"], imgUrl);
    }
    if (img) {
      YAHOO.util.Dom.addClass(img, "img_zero_click_big");
      div = d.createElement("div");
      div.appendChild(img);
      snippet.appendChild(div);
      link = d.createElement("a");
      link.href = "/?q=xkcd " + (parseInt(xk["num"]) - 1);
      link.appendChild(d.createTextNode("Prev"));
      snippet.appendChild(link);
      snippet.appendChild(d.createTextNode("   "));
    }
    items = new Array();
    items[0] = new Array();
    items[0]["a"] = snippet;
    items[0]["h"] = xk["safe_title"] + " (XKCD)";
    items[0]["s"] = "XKCD";
    items[0]["u"] = "http://xkcd.com/" + xk["num"];
    items[0]["f"] = 1;
    return nra(items);
  }
};
