// Generated by CoffeeScript 1.4.0
(function() {
  var root;

  root = this;

  root.detect_lang.debug = true;

  describe("Detect Language:", function() {
    it("correctly detects a known query", function() {
      var json, result;
      json = {
        data: {
          detections: [
            {
              language: 'es',
              isReliable: false,
              confidence: 0.4517133956386293
            }, {
              language: 'pt',
              isReliable: false,
              confidence: 0.08356545961002786
            }
          ]
        }
      };
      result = {
        detections: [
          {
            language: 'Spanish',
            confidence: '(45% sure)'
          }, {
            language: 'Portuguese',
            confidence: '(8% sure)'
          }
        ]
      };
      return expect(ddg_spice_detect_lang(json)).toEqual(result);
    });
    it("returns an undefined when 'detections' is empty", function() {
      var json;
      json = {
        data: {
          detections: []
        }
      };
      return expect(ddg_spice_detect_lang(json)).toBe(void 0);
    });
    it("returns an undefined when 'detections' does not exist", function() {
      var json;
      json = {
        data: {}
      };
      return expect(ddg_spice_detect_lang(json)).toBe(void 0);
    });
    it("returns an undefined when 'data' does not exist", function() {
      var json;
      json = {};
      return expect(ddg_spice_detect_lang(json)).toBe(void 0);
    });
    it("shows a single language when a single language is found", function() {
      var json, result;
      json = {
        data: {
          detections: [
            {
              language: 'es',
              isReliable: false,
              confidence: 0.4517133956386293
            }
          ]
        }
      };
      result = {
        detections: [
          {
            language: 'Spanish',
            confidence: '(45% sure)'
          }
        ]
      };
      return expect(ddg_spice_detect_lang(json)).toEqual(result);
    });
    return it("returns an empty array when the language code does not exist in our dictionary", function() {
      var json;
      json = {
        data: {
          detections: [
            {
              language: 'lol',
              isReliable: false,
              confidence: 0.4517133956386293
            }, {
              language: 'lmfao',
              isReliable: false,
              confidence: 0.08356545961002786
            }
          ]
        }
      };
      return expect(ddg_spice_detect_lang(json)).toEqual({
        detections: []
      });
    });
  });

}).call(this);
