// Generated by CoffeeScript 1.4.0
(function() {
  var langs, root, sortConfidence, toPercent;

  root = this;

  root.detect_lang = {};

  langs = {
    'af': 'Afrikaans',
    'ar': 'Arabic',
    'be': 'Belarusian',
    'bg': 'Bulgarian',
    'ca': 'Catalan',
    'chr': 'Cherokee',
    'cs': 'Czech',
    'cy': 'Welsh',
    'da': 'Danish',
    'de': 'German',
    'dv': 'Dhivehi',
    'el': 'Greek',
    'en': 'English',
    'es': 'Spanish',
    'et': 'Estonian',
    'fa': 'Persian',
    'fi': 'Finnish',
    'fil': 'Tagalog',
    'fr': 'French',
    'ga': 'Irish',
    'gu': 'Gujarati',
    'he': 'Hebrew',
    'hi': 'Hindi',
    'hr': 'Croatian',
    'hu': 'Hungarian',
    'hy': 'Armenian',
    'is': 'Icelandic',
    'it': 'Italian',
    'iu': 'Inuktitut',
    'ja': 'Japanese',
    'ka': 'Georgian',
    'km': 'Khmer',
    'kn': 'Kannada',
    'ko': 'Korean',
    'lo': 'Laothian',
    'lt': 'Lithuanian',
    'lv': 'Latvian',
    'mk': 'Macedonian',
    'ml': 'Malayalam',
    'ms': 'Malay',
    'nb': 'Norwegian',
    'nl': 'Dutch',
    'or': 'Oriya',
    'pa': 'Punjabi',
    'pl': 'Polish',
    'pt': 'Portuguese',
    'ro': 'Romanian',
    'ru': 'Russian',
    'si': 'Sinhalese',
    'sk': 'Slovak',
    'sl': 'Slovenian',
    'sr': 'Serbian',
    'sv': 'Swedish',
    'sw': 'Swahili',
    'syr': 'Syriac',
    'ta': 'Tamil',
    'te': 'Telugu',
    'th': 'Thai',
    'tr': 'Turkish',
    'uk': 'Ukrainian',
    'vi': 'Vietnamese',
    'yi': 'Yiddish',
    'zh': 'Chinese',
    'zh-TW': 'Chineset'
  };

  sortConfidence = function(a, b) {
    return a.confidence < b.confidence;
  };

  toPercent = function(number) {
    if (number == null) {
      number = 0;
    }
    return "(" + (Math.round(number * 100)) + "% sure)";
  };

  root.ddg_spice_detect_lang = function(language) {
    var detections, element, items, query, result, _ref;
    items = [];
    detections = language != null ? (_ref = language.data) != null ? _ref.detections : void 0 : void 0;
    if (detections && detections.length > 0) {
      detections.sort(sortConfidence);
      detections = (function() {
        var _i, _len, _results;
        _results = [];
        for (_i = 0, _len = detections.length; _i < _len; _i++) {
          element = detections[_i];
          if ((langs[element.language] != null) && (element.confidence != null)) {
            _results.push({
              language: langs[element.language],
              confidence: toPercent(element.confidence)
            });
          }
        }
        return _results;
      })();
      if (detections.length === 1) {
        result = "This text is probably " + detections[0].language + " " + detections[0].confidence + ".";
      } else if (detections.length > 1) {
        result = "This text is probably " + detections[0].language + " " + detections[0].confidence;
        result += ", but it could also be " + detections[1].language + " " + detections[1].confidence + ".";
      }
      if (root.detect_lang.debug === true) {
        return {
          detections: detections
        };
      } else if (result != null) {
        query = DDG.get_query().replace(/(?:detect|identify|what|determine|check)\s+language/, "");
        query = query.replace(/^\s+|\s+$/g, "");
        items[0] = {
          h: "" + query + " (Language Detection)",
          s: "detectlanguage.com",
          u: "http://detectlanguage.com",
          force_big_header: true,
          force_space_after: true,
          a: result
        };
        return nra(items);
      }
    }
  };

}).call(this);
