af: "afn"
ax: "eur"
al: "all"
dz: "dzd"
as: "usd"
ad: "eur"
ao: "aoa"
ai: "xcd"
ag: "xcd"
ar: "ars"
am: "amd"
aw: "awg"
au: "aud"
at: "eur"
az: "azn"
bs: "bsd"
bh: "bhd"
bd: "bdt"
bb: "bbd"
by: "byn"
be: "eur"
bz: "bzd"
bj: "xof"
bm: "bmd"
bt: "inr"
bo: "bob"
bq: "usd"
ba: "bam"
bw: "bwp"
bv: "nok"
br: "brl"
io: "usd"
bn: "bnd"
bg: "bgn"
bf: "xof"
bi: "bif"
cv: "cve"
kh: "khr"
cm: "xaf"
ca: "cad"
ky: "kyd"
cf: "xaf"
td: "xaf"
cl: "clp"
cn: "cny"
cx: "aud"
cc: "aud"
co: "cop"
km: "kmf"
cd: "cdf"
cg: "xaf"
ck: "nzd"
cr: "crc"
ci: "xof"
hr: "hrk"
cu: "cup"
cw: "ang"
cy: "eur"
cz: "czk"
dk: "dkk"
dj: "djf"
dm: "xcd"
do: "dop"
ec: "usd"
eg: "egp"
sv: "svc"
gq: "xaf"
er: "ern"
ee: "eur"
et: "etb"
fk: "fkp"
fo: "dkk"
fj: "fjd"
fi: "eur"
fr: "eur"
gf: "eur"
pf: "xpf"
tf: "eur"
ga: "xaf"
gm: "gmd"
ge: "gel"
de: "eur"
gh: "ghs"
gi: "gip"
gr: "eur"
gl: "dkk"
gd: "xcd"
gp: "eur"
gu: "usd"
gt: "gtq"
gg: "gbp"
gn: "gnf"
gw: "xof"
gy: "gyd"
ht: "htg"
hm: "aud"
va: "eur"
hn: "hnl"
hk: "hkd"
hu: "huf"
is: "isk"
in: "inr"
id: "idr"
ir: "irr"
iq: "iqd"
ie: "eur"
im: "gbp"
il: "ils"
it: "eur"
jm: "jmd"
jp: "jpy"
je: "gbp"
jo: "jod"
kz: "kzt"
ke: "kes"
ki: "aud"
kp: "kpw"
kr: "krw"
kw: "kwd"
kg: "kgs"
la: "lak"
lv: "eur"
lb: "lbp"
ls: "lsl"
lr: "lrd"
ly: "lyd"
li: "chf"
lt: "eur"
lu: "eur"
mo: "mop"
mk: "mkd"
mg: "mga"
mw: "mwk"
my: "myr"
mv: "mvr"
ml: "xof"
mt: "eur"
mh: "usd"
mq: "eur"
mr: "mro"
mu: "mur"
yt: "eur"
mx: "mxn"
fm: "usd"
md: "mdl"
mc: "eur"
mn: "mnt"
me: "eur"
ms: "xcd"
ma: "mad"
mz: "mzn"
mm: "mmk"
na: "nad"
nr: "aud"
np: "npr"
nl: "eur"
nc: "xpf"
nz: "nzd"
ni: "nio"
ne: "xof"
ng: "ngn"
nu: "nzd"
nf: "aud"
mp: "usd"
no: "nok"
om: "omr"
pk: "pkr"
pw: "usd"
pa: "pab"
pg: "pgk"
py: "pyg"
pe: "pen"
ph: "php"
pn: "nzd"
pl: "pln"
pt: "eur"
pr: "usd"
qa: "qar"
re: "eur"
ro: "ron"
ru: "rub"
rw: "rwf"
bl: "eur"
sh: "shp"
kn: "xcd"
lc: "xcd"
mf: "eur"
pm: "eur"
vc: "xcd"
ws: "wst"
sm: "eur"
st: "std"
sa: "sar"
sn: "xof"
rs: "rsd"
sc: "scr"
sl: "sll"
sg: "sgd"
sx: "ang"
sk: "eur"
si: "eur"
sb: "sbd"
so: "sos"
za: "zar"
ss: "ssp"
es: "eur"
lk: "lkr"
sd: "sdg"
sr: "srd"
sj: "nok"
sz: "szl"
se: "sek"
ch: "chf"
sy: "syp"
tw: "twd"
tj: "tjk"
tz: "tas"
th: "thb"
tl: "usd"
tg: "xof"
tk: "nzd"
to: "top"
tt: "ttd"
tn: "tnd"
tr: "try"
tm: "tmt"
tc: "usd"
tv: "aud"
ug: "ugx"
ua: "uah"
ae: "aed"
gb: "gbp"
us: "usd"
um: "usd"
uy: "uyu"
uz: "uzs"
vu: "vuv"
ve: "vef"
vn: "vnd"
vg: "usd"
vi: "usd"
wf: "xpf"
eh: "mad"
ye: "yer"
zm: "zmb"
zw: "zwl"