#!/usr/bin/env perl

use strict;
use warnings;
use Test::More;
use DDG::Test::Spice;

ddg_spice_test(
  [qw(DDG::Spice::Symbolab)],
  "integrate 1/sqrt(1-y^2)" => test_spice(
    '/js/spice/symbolab/integrate%201%2Fsqrt%281-y%5E2%29',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "integrate e^sinx cosx dx" => test_spice(
    '/js/spice/symbolab/integrate%20e%5Esinx%20cosx%20dx',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "derivative of ln" => test_spice(
    '/js/spice/symbolab/derivative%20of%20ln',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "integration 2x" => test_spice(
    '/js/spice/symbolab/integration%202x',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "derivative of sqrt(2x)" => test_spice(
    '/js/spice/symbolab/derivative%20of%20sqrt%282x%29',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "integral of tan u" => test_spice(
    '/js/spice/symbolab/integral%20of%20tan%20u',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "calculate integral of x^2" => test_spice(
    '/js/spice/symbolab/calculate%20integral%20of%20x%5E2',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "calculate x^2-1=0" => test_spice(
    '/js/spice/symbolab/calculate%20x%5E2-1%3D0',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "calculate \\tan(x)=0" => test_spice(
    '/js/spice/symbolab/calculate%20%5Ctan%28x%29%3D0',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "integral of x^2" => test_spice(
    '/js/spice/symbolab/integral%20of%20x%5E2',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "integrate x^2" => test_spice(
    '/js/spice/symbolab/integrate%20x%5E2',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "integration of x^2" => test_spice(
    '/js/spice/symbolab/integration%20of%20x%5E2',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "antiderivative of x^2" => test_spice(
    '/js/spice/symbolab/antiderivative%20of%20x%5E2',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "derivative of x^2" => test_spice(
    '/js/spice/symbolab/derivative%20of%20x%5E2',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "derive x^2" => test_spice(
    '/js/spice/symbolab/derive%20x%5E2',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "integral x^3/e^x-1" => test_spice(
    '/js/spice/symbolab/integral%20x%5E3%2Fe%5Ex-1',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "integral of x^2 dx" => test_spice(
    '/js/spice/symbolab/integral%20of%20x%5E2%20dx',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "integrate sin^9 x dx" => test_spice(
    '/js/spice/symbolab/integrate%20sin%5E9%20x%20dx',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "integrate sin 3t dt" => test_spice(
    '/js/spice/symbolab/integrate%20sin%203t%20dt',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "derivative of lnx" => test_spice(
    '/js/spice/symbolab/derivative%20of%20lnx',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "solve (-5i)(-i)" => test_spice(
    '/js/spice/symbolab/solve%20%28-5i%29%28-i%29',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "integral of lnx" => test_spice(
    '/js/spice/symbolab/integral%20of%20lnx',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "integration sin 2x" => test_spice(
    '/js/spice/symbolab/integration%20sin%202x',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "integral ln8x+1" => test_spice(
    '/js/spice/symbolab/integral%20ln8x%2B1',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "derivative of sin x" => test_spice(
    '/js/spice/symbolab/derivative%20of%20sin%20x',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "integral of ln(x)" => test_spice(
    '/js/spice/symbolab/integral%20of%20ln%28x%29',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "integrate 2/x^2+1" => test_spice(
    '/js/spice/symbolab/integrate%202%2Fx%5E2%2B1',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "integral of 1/x" => test_spice(
    '/js/spice/symbolab/integral%20of%201%2Fx',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "integral of secx" => test_spice(
    '/js/spice/symbolab/integral%20of%20secx',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "integral sinxcosx" => test_spice(
    '/js/spice/symbolab/integral%20sinxcosx',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "integrate sqrt(1-x^2)" => test_spice(
    '/js/spice/symbolab/integrate%20sqrt%281-x%5E2%29',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "solve 50-4i" => test_spice(
    '/js/spice/symbolab/solve%2050-4i',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "derivative of x^(x^2)" => test_spice(
    '/js/spice/symbolab/derivative%20of%20x%5E%28x%5E2%29',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "solve (i)(-i)" => test_spice(
    '/js/spice/symbolab/solve%20%28i%29%28-i%29',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "integral of sinxcosx" => test_spice(
    '/js/spice/symbolab/integral%20of%20sinxcosx',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "integrate sinh 3t dt" => test_spice(
    '/js/spice/symbolab/integrate%20sinh%203t%20dt',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "derivative of ce^x" => test_spice(
    '/js/spice/symbolab/derivative%20of%20ce%5Ex',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "solve (2-5i)(1-i)+(7+i)(7-i)" => test_spice(
    '/js/spice/symbolab/solve%20%282-5i%29%281-i%29%2B%287%2Bi%29%287-i%29',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "solve (-7i) + 7i" => test_spice(
    '/js/spice/symbolab/solve%20%28-7i%29%20%2B%207i',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "integral of tan x" => test_spice(
    '/js/spice/symbolab/integral%20of%20tan%20x',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "integral sin(x)/x" => test_spice(
    '/js/spice/symbolab/integral%20sin%28x%29%2Fx',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "integration tanx" => test_spice(
    '/js/spice/symbolab/integration%20tanx',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "solve |5x-5|=18" => test_spice(
    '/js/spice/symbolab/solve%20%7C5x-5%7C%3D18',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "derivative of sec(x)" => test_spice(
    '/js/spice/symbolab/derivative%20of%20sec%28x%29',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "antiderivative of sec x" => test_spice(
    '/js/spice/symbolab/antiderivative%20of%20sec%20x',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "derivative e^x" => test_spice(
    '/js/spice/symbolab/derivative%20e%5Ex',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "derivative of tanx" => test_spice(
    '/js/spice/symbolab/derivative%20of%20tanx',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "derivative ln x" => test_spice(
    '/js/spice/symbolab/derivative%20ln%20x',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "antiderivative of 1/x" => test_spice(
    '/js/spice/symbolab/antiderivative%20of%201%2Fx',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "solve 50+i+(-5i)" => test_spice(
    '/js/spice/symbolab/solve%2050%2Bi%2B%28-5i%29',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "derivative of cos x" => test_spice(
    '/js/spice/symbolab/derivative%20of%20cos%20x',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "integral 1/x" => test_spice(
    '/js/spice/symbolab/integral%201%2Fx',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "derivative of sin^2(x)" => test_spice(
    '/js/spice/symbolab/derivative%20of%20sin%5E2%28x%29',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "integrate 1/((x^2 + 9)(x^2 + 4))" => test_spice(
    '/js/spice/symbolab/integrate%201%2F%28%28x%5E2%20%2B%209%29%28x%5E2%20%2B%204%29%29',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "integrate e^-1z" => test_spice(
    '/js/spice/symbolab/integrate%20e%5E-1z',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "solve 7/2(5pi/2)^2" => test_spice(
    '/js/spice/symbolab/solve%207%2F2%285pi%2F2%29%5E2',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "derivative of e^x" => test_spice(
    '/js/spice/symbolab/derivative%20of%20e%5Ex',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "derivative of a^x" => test_spice(
    '/js/spice/symbolab/derivative%20of%20a%5Ex',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "derivative of tan x" => test_spice(
    '/js/spice/symbolab/derivative%20of%20tan%20x',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "integral e^x" => test_spice(
    '/js/spice/symbolab/integral%20e%5Ex',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "integral t^3 sqrt(1+t^29" => test_spice(
    '/js/spice/symbolab/integral%20t%5E3%20sqrt%281%2Bt%5E29',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "integrate cos2t" => test_spice(
    '/js/spice/symbolab/integrate%20cos2t',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "integrate x-1" => test_spice(
    '/js/spice/symbolab/integrate%20x-1',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "derivative of log (a*x^b)" => test_spice(
    '/js/spice/symbolab/derivative%20of%20log%20%28a%2Ax%5Eb%29',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "integral of e^x" => test_spice(
    '/js/spice/symbolab/integral%20of%20e%5Ex',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "derivative of sqrt(x)*(x-8)" => test_spice(
    '/js/spice/symbolab/derivative%20of%20sqrt%28x%29%2A%28x-8%29',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "derivative of -cosx" => test_spice(
    '/js/spice/symbolab/derivative%20of%20-cosx',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "integrate z/((z-3)(z-2)) at |z|=2.5" => test_spice(
    '/js/spice/symbolab/integrate%20z%2F%28%28z-3%29%28z-2%29%29%20at%20%7Cz%7C%3D2.5',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "integrate e^5t" => test_spice(
    '/js/spice/symbolab/integrate%20e%5E5t',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "integrate t*cos(ht)" => test_spice(
    '/js/spice/symbolab/integrate%20t%2Acos%28ht%29',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "derivative of x^(1/4)-4e^x" => test_spice(
    '/js/spice/symbolab/derivative%20of%20x%5E%281%2F4%29-4e%5Ex',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "derivative e^(1/x)" => test_spice(
    '/js/spice/symbolab/derivative%20e%5E%281%2Fx%29',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "derivative of ln2x" => test_spice(
    '/js/spice/symbolab/derivative%20of%20ln2x',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "derivative of ln(x)" => test_spice(
    '/js/spice/symbolab/derivative%20of%20ln%28x%29',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "sqrt 2 calculate" => test_spice(
    '/js/spice/symbolab/sqrt%202%20calculate',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "integrate cos^2x" => test_spice(
    '/js/spice/symbolab/integrate%20cos%5E2x',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "integrate sec(x)" => test_spice(
    '/js/spice/symbolab/integrate%20sec%28x%29',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "derivative 10^x^2" => test_spice(
    '/js/spice/symbolab/derivative%2010%5Ex%5E2',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "integral xe^x" => test_spice(
    '/js/spice/symbolab/integral%20xe%5Ex',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "integral of cscx" => test_spice(
    '/js/spice/symbolab/integral%20of%20cscx',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "derivative of cotx" => test_spice(
    '/js/spice/symbolab/derivative%20of%20cotx',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "integral of e^(3x)" => test_spice(
    '/js/spice/symbolab/integral%20of%20e%5E%283x%29',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "integration of 1/(1+x)^2" => test_spice(
    '/js/spice/symbolab/integration%20of%201%2F%281%2Bx%29%5E2',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "derivative of x^x" => test_spice(
    '/js/spice/symbolab/derivative%20of%20x%5Ex',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "integrate x e^x dx" => test_spice(
    '/js/spice/symbolab/integrate%20x%20e%5Ex%20dx',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "integral (e^x+1)^2" => test_spice(
    '/js/spice/symbolab/integral%20%28e%5Ex%2B1%29%5E2',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "derivative of (1/x)" => test_spice(
    '/js/spice/symbolab/derivative%20of%20%281%2Fx%29',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "integral t^3 sqrt(1+t^2)" => test_spice(
    '/js/spice/symbolab/integral%20t%5E3%20sqrt%281%2Bt%5E2%29',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "differentiate x^3/27" => test_spice(
    '/js/spice/symbolab/differentiate%20x%5E3%2F27',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "integrate cosx" => test_spice(
    '/js/spice/symbolab/integrate%20cosx',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "integral pf lnx" => test_spice(
    '/js/spice/symbolab/integral%20pf%20lnx',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "derivative of secx" => test_spice(
    '/js/spice/symbolab/derivative%20of%20secx',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "integral cos4x" => test_spice(
    '/js/spice/symbolab/integral%20cos4x',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "integrate x^x" => test_spice(
    '/js/spice/symbolab/integrate%20x%5Ex',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "integral x1/2 - cos x" => test_spice(
    '/js/spice/symbolab/integral%20x1%2F2%20-%20cos%20x',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "differentiate dn/n" => test_spice(
    '/js/spice/symbolab/differentiate%20dn%2Fn',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "cot(3x) = cos(3x)" => test_spice(
    '/js/spice/symbolab/cot%283x%29%20%3D%20cos%283x%29',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "derivative of sin(2t)" => test_spice(
    '/js/spice/symbolab/derivative%20of%20sin%282t%29',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "derivative of 9e^x" => test_spice(
    '/js/spice/symbolab/derivative%20of%209e%5Ex',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "derivative cos^5(x)" => test_spice(
    '/js/spice/symbolab/derivative%20cos%5E5%28x%29',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "derivative of 2/(t+1)" => test_spice(
    '/js/spice/symbolab/derivative%20of%202%2F%28t%2B1%29',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "derivative of x^-1/2" => test_spice(
    '/js/spice/symbolab/derivative%20of%20x%5E-1%2F2',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "integrate x/(x^2+ 2x +2)" => test_spice(
    '/js/spice/symbolab/integrate%20x%2F%28x%5E2%2B%202x%20%2B2%29',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "integral 1/pi x" => test_spice(
    '/js/spice/symbolab/integral%201%2Fpi%20x',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "derivative of log a*x^b" => test_spice(
    '/js/spice/symbolab/derivative%20of%20log%20a%2Ax%5Eb',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "integration tan 3x" => test_spice(
    '/js/spice/symbolab/integration%20tan%203x',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "integral of cos x" => test_spice(
    '/js/spice/symbolab/integral%20of%20cos%20x',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "integral of tan y" => test_spice(
    '/js/spice/symbolab/integral%20of%20tan%20y',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "derivation a^x" => test_spice(
    '/js/spice/symbolab/derivation%20a%5Ex',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "log10(2)" => test_spice(
    '/js/spice/symbolab/log10%282%29',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "a^x integral" => test_spice(
    '/js/spice/symbolab/a%5Ex%20integral',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "integrate sin h 3t dt" => test_spice(
    '/js/spice/symbolab/integrate%20sin%20h%203t%20dt',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "integral of e^3x" => test_spice(
    '/js/spice/symbolab/integral%20of%20e%5E3x',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "derivative of ln x" => test_spice(
    '/js/spice/symbolab/derivative%20of%20ln%20x',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "integrate sqrt(x^2+1)" => test_spice(
    '/js/spice/symbolab/integrate%20sqrt%28x%5E2%2B1%29',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "solve -1^2" => test_spice(
    '/js/spice/symbolab/solve%20-1%5E2',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "log(2)" => test_spice(
    '/js/spice/symbolab/log%282%29',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "integral 1/(1+x^2)" => test_spice(
    '/js/spice/symbolab/integral%201%2F%281%2Bx%5E2%29',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "integrate xe^x dx" => test_spice(
    '/js/spice/symbolab/integrate%20xe%5Ex%20dx',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "solve .05/6" => test_spice(
    '/js/spice/symbolab/solve%20.05%2F6',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "integrate 2x^3-4x^2-15x+5/x-4" => test_spice(
    '/js/spice/symbolab/integrate%202x%5E3-4x%5E2-15x%2B5%2Fx-4',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "derivative lnx" => test_spice(
    '/js/spice/symbolab/derivative%20lnx',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "derivative of sin4x" => test_spice(
    '/js/spice/symbolab/derivative%20of%20sin4x',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "derivative of x+ke^x" => test_spice(
    '/js/spice/symbolab/derivative%20of%20x%2Bke%5Ex',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "solve 2 3/2" => test_spice(
    '/js/spice/symbolab/solve%202%203%2F2',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "(-x^2)" => test_spice(
    '/js/spice/symbolab/%28-x%5E2%29',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "integrate 5^x" => test_spice(
    '/js/spice/symbolab/integrate%205%5Ex',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "integral of 1/x^2" => test_spice(
    '/js/spice/symbolab/integral%20of%201%2Fx%5E2',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "derivative of e^-x" => test_spice(
    '/js/spice/symbolab/derivative%20of%20e%5E-x',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "derivative of log (ax^b)" => test_spice(
    '/js/spice/symbolab/derivative%20of%20log%20%28ax%5Eb%29',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "derivative of 1/x^2" => test_spice(
    '/js/spice/symbolab/derivative%20of%201%2Fx%5E2',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "integral of sin 2x dx" => test_spice(
    '/js/spice/symbolab/integral%20of%20sin%202x%20dx',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "derivative of log(x)" => test_spice(
    '/js/spice/symbolab/derivative%20of%20log%28x%29',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "integrate sin^4 x" => test_spice(
    '/js/spice/symbolab/integrate%20sin%5E4%20x',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "integrate x/(sqrt(x^2 - 16))" => test_spice(
    '/js/spice/symbolab/integrate%20x%2F%28sqrt%28x%5E2%20-%2016%29%29',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "integral ln(cos(x))" => test_spice(
    '/js/spice/symbolab/integral%20ln%28cos%28x%29%29',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "integral of 1/2x" => test_spice(
    '/js/spice/symbolab/integral%20of%201%2F2x',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "integrate sin x^2" => test_spice(
    '/js/spice/symbolab/integrate%20sin%20x%5E2',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "integrate sec^5 x" => test_spice(
    '/js/spice/symbolab/integrate%20sec%5E5%20x',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "integral of sin5xcos2x" => test_spice(
    '/js/spice/symbolab/integral%20of%20sin5xcos2x',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "integral 3^x" => test_spice(
    '/js/spice/symbolab/integral%203%5Ex',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "integrate dn/n" => test_spice(
    '/js/spice/symbolab/integrate%20dn%2Fn',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "integrate sinh3tdt" => test_spice(
    '/js/spice/symbolab/integrate%20sinh3tdt',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "derivative of x^1/2" => test_spice(
    '/js/spice/symbolab/derivative%20of%20x%5E1%2F2',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "integrate 1/(a-x)" => test_spice(
    '/js/spice/symbolab/integrate%201%2F%28a-x%29',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "integrate e^5t dt" => test_spice(
    '/js/spice/symbolab/integrate%20e%5E5t%20dt',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "solve -4/5 +1" => test_spice(
    '/js/spice/symbolab/solve%20-4%2F5%20%2B1',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "derivative of log x" => test_spice(
    '/js/spice/symbolab/derivative%20of%20log%20x',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "x^x derivative" => test_spice(
    '/js/spice/symbolab/x%5Ex%20derivative',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "integral of sin^2(x)" => test_spice(
    '/js/spice/symbolab/integral%20of%20sin%5E2%28x%29',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "integral tan x" => test_spice(
    '/js/spice/symbolab/integral%20tan%20x',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "derivative of cos4x" => test_spice(
    '/js/spice/symbolab/derivative%20of%20cos4x',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "derivative of cosx" => test_spice(
    '/js/spice/symbolab/derivative%20of%20cosx',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "integral of 1/(2x+1)" => test_spice(
    '/js/spice/symbolab/integral%20of%201%2F%282x%2B1%29',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "integrate tan x" => test_spice(
    '/js/spice/symbolab/integrate%20tan%20x',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "integral of 1/(99-3x)dx" => test_spice(
    '/js/spice/symbolab/integral%20of%201%2F%2899-3x%29dx',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "integrate t/(t^2+1)" => test_spice(
    '/js/spice/symbolab/integrate%20t%2F%28t%5E2%2B1%29',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "derivative of x^2" => test_spice(
    '/js/spice/symbolab/derivative%20of%20x%5E2',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "sin kr integral" => test_spice(
    '/js/spice/symbolab/sin%20kr%20integral',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "integral of (x-k)f(x)dx" => test_spice(
    '/js/spice/symbolab/integral%20of%20%28x-k%29f%28x%29dx',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "solve 180/pi" => test_spice(
    '/js/spice/symbolab/solve%20180%2Fpi',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "integral cosx2" => test_spice(
    '/js/spice/symbolab/integral%20cosx2',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "integral of y/(y+1)" => test_spice(
    '/js/spice/symbolab/integral%20of%20y%2F%28y%2B1%29',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "solve (-5i)1" => test_spice(
    '/js/spice/symbolab/solve%20%28-5i%291',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "derivative of sin2x" => test_spice(
    '/js/spice/symbolab/derivative%20of%20sin2x',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "solve (-5i)+2i" => test_spice(
    '/js/spice/symbolab/solve%20%28-5i%29%2B2i',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "solve -(-5)" => test_spice(
    '/js/spice/symbolab/solve%20-%28-5%29',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "integration of logx" => test_spice(
    '/js/spice/symbolab/integration%20of%20logx',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "integral cos(4*x)" => test_spice(
    '/js/spice/symbolab/integral%20cos%284%2Ax%29',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "derivative of e^u" => test_spice(
    '/js/spice/symbolab/derivative%20of%20e%5Eu',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "integral of x^2lnx" => test_spice(
    '/js/spice/symbolab/integral%20of%20x%5E2lnx',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "e^x derivative" => test_spice(
    '/js/spice/symbolab/e%5Ex%20derivative',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "derivative of x/(1-x^2)^3/2" => test_spice(
    '/js/spice/symbolab/derivative%20of%20x%2F%281-x%5E2%29%5E3%2F2',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "integral of log x" => test_spice(
    '/js/spice/symbolab/integral%20of%20log%20x',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "solve (2i)*1" => test_spice(
    '/js/spice/symbolab/solve%20%282i%29%2A1',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "integral of ln(x+1)" => test_spice(
    '/js/spice/symbolab/integral%20of%20ln%28x%2B1%29',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "derivative of tan" => test_spice(
    '/js/spice/symbolab/derivative%20of%20tan',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "integral of e^-x" => test_spice(
    '/js/spice/symbolab/integral%20of%20e%5E-x',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "integral csc^2" => test_spice(
    '/js/spice/symbolab/integral%20csc%5E2',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "solve (-5i)" => test_spice(
    '/js/spice/symbolab/solve%20%28-5i%29',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "derivative of cos" => test_spice(
    '/js/spice/symbolab/derivative%20of%20cos',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "derivative of sin" => test_spice(
    '/js/spice/symbolab/derivative%20of%20sin',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "integral of e^-x" => test_spice(
    '/js/spice/symbolab/integral%20of%20e%5E-x',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "integral csc^2" => test_spice(
    '/js/spice/symbolab/integral%20csc%5E2',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "solve (-5i)" => test_spice(
    '/js/spice/symbolab/solve%20%28-5i%29',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "derivative of arctan" => test_spice(
    '/js/spice/symbolab/derivative%20of%20arctan',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "integrate sin^2" => test_spice(
    '/js/spice/symbolab/integrate%20sin%5E2',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "integrate t^2 sint dt" => test_spice(
    '/js/spice/symbolab/integrate%20t%5E2%20sint%20dt',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "integral csc^4" => test_spice(
    '/js/spice/symbolab/integral%20csc%5E4',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "derive de log" => test_spice(
    '/js/spice/symbolab/derive%20de%20log',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "derivative of sin 2" => test_spice(
    '/js/spice/symbolab/derivative%20of%20sin%202',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "derivative csc" => test_spice(
    '/js/spice/symbolab/derivative%20csc',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "integral t^7e^-t^4" => test_spice(
    '/js/spice/symbolab/integral%20t%5E7e%5E-t%5E4',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "integral ln" => test_spice(
    '/js/spice/symbolab/integral%20ln',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "derivative of cos" => test_spice(
    '/js/spice/symbolab/derivative%20of%20cos',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "integral of cos" => test_spice(
    '/js/spice/symbolab/integral%20of%20cos',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "derivative tan" => test_spice(
    '/js/spice/symbolab/derivative%20tan',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "cos derivative" => test_spice(
    '/js/spice/symbolab/cos%20derivative',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "integral of tan" => test_spice(
    '/js/spice/symbolab/integral%20of%20tan',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "integrate e^-x" => test_spice(
    '/js/spice/symbolab/integrate%20e%5E-x',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "integral csc^m" => test_spice(
    '/js/spice/symbolab/integral%20csc%5Em',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "derivative of sec" => test_spice(
    '/js/spice/symbolab/derivative%20of%20sec',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "tanh derivative" => test_spice(
    '/js/spice/symbolab/tanh%20derivative',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "derivative cos" => test_spice(
    '/js/spice/symbolab/derivative%20cos',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "integrate x/(x^2 2x +2)" => test_spice(
    '/js/spice/symbolab/integrate%20x%2F%28x%5E2%202x%20%2B2%29',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "derivative of log" => test_spice(
    '/js/spice/symbolab/derivative%20of%20log',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "antiderivative of sec^2" => test_spice(
    '/js/spice/symbolab/antiderivative%20of%20sec%5E2',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "integral csc" => test_spice(
    '/js/spice/symbolab/integral%20csc',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "integrate \"x/(x^2+ 2x +2)\"" => test_spice(
    '/js/spice/symbolab/integrate%20%22x%2F%28x%5E2%2B%202x%20%2B2%29%22',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "derivative of a log" => test_spice(
    '/js/spice/symbolab/derivative%20of%20a%20log',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "derivative of cos x+y" => test_spice(
    '/js/spice/symbolab/derivative%20of%20cos%20x%2By',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "integral cos" => test_spice(
    '/js/spice/symbolab/integral%20cos',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "derivative of cos^(2)" => test_spice(
    '/js/spice/symbolab/derivative%20of%20cos%5E%282%29',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "integral sin*cos" => test_spice(
    '/js/spice/symbolab/integral%20sin%2Acos',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "integral sinus" => test_spice(
    '/js/spice/symbolab/integral%20sinus',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "solve a * dx/dt + b * x + c = 0" => test_spice(
    '/js/spice/symbolab/solve%20a%20%2A%20dx%2Fdt%20%2B%20b%20%2A%20x%20%2B%20c%20%3D%200',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "solve ax^3 + bx + c = 0" => test_spice(
    '/js/spice/symbolab/solve%20ax%5E3%20%2B%20bx%20%2B%20c%20%3D%200',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "integrate cos^2" => test_spice(
    '/js/spice/symbolab/integrate%20cos%5E2',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "integral -inf +inf t" => test_spice(
    '/js/spice/symbolab/integral%20-inf%20%2Binf%20t',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "integral of sen^2" => test_spice(
    '/js/spice/symbolab/integral%20of%20sen%5E2',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "derive f*g*h" => test_spice(
    '/js/spice/symbolab/derive%20f%2Ag%2Ah',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "integral of tan y dy" => test_spice(
    '/js/spice/symbolab/integral%20of%20tan%20y%20dy',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "integration of x^-1" => test_spice(
    '/js/spice/symbolab/integration%20of%20x%5E-1',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "integral de 1/(1+2t)" => test_spice(
    '/js/spice/symbolab/integral%20de%201%2F%281%2B2t%29',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "csc integral" => test_spice(
    '/js/spice/symbolab/csc%20integral',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "integrate 1/cos" => test_spice(
    '/js/spice/symbolab/integrate%201%2Fcos',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "(-2x+1+x^2) solve" => test_spice(
    '/js/spice/symbolab/%28-2x%2B1%2Bx%5E2%29%20solve',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "integral of csc^2" => test_spice(
    '/js/spice/symbolab/integral%20of%20csc%5E2',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "derivative of log10" => test_spice(
    '/js/spice/symbolab/derivative%20of%20log10',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "derivative sec" => test_spice(
    '/js/spice/symbolab/derivative%20sec',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "derivative of sin" => test_spice(
    '/js/spice/symbolab/derivative%20of%20sin',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "integral of ln" => test_spice(
    '/js/spice/symbolab/integral%20of%20ln',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "integrate x^-1" => test_spice(
    '/js/spice/symbolab/integrate%20x%5E-1',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "integral \"ln8x+1\"" => test_spice(
    '/js/spice/symbolab/integral%20%22ln8x%2B1%22',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "x^2+2=0" => test_spice(
    '/js/spice/symbolab/x%5E2%2B2%3D0',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "x^2+2x=3" => test_spice(
    '/js/spice/symbolab/x%5E2%2B2x%3D3',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "factor x^2-2" => test_spice(
    '/js/spice/symbolab/factor%20x%5E2-2',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "expand (x+y)^3" => test_spice(
    '/js/spice/symbolab/expand%20%28x%2By%29%5E3',
    call_type => 'include',
    caller => 'DDG::Spice::Symbolab',
    is_cashed => 1,
  ),
  "instant" => undef,
  "reverse>=0:purpose+integration+knowledge+evaluation=0<nullify" => undef,
  "derivative of a vector function" => undef,
  "integral " => undef,
  "current version plugin gnome shell integration " => undef,
  "continuous integration " => undef,
  "integration by parts" => undef,
  "line integral" => undef,
  "integral calculator" => undef,
  "derivative of a summation" => undef,
  "integral ad science" => undef,
  "derivative of a pmf" => undef,
  "integration vs unit tests" => undef,
  "calculate" => undef,
  "calculate mortgage" => undef,
  "c++ time series integration" => undef,
  "c++ numeric integration" => undef,
  "distance between numbers c++" => undef,
  "kde owncloud setup kaccounts-integration" => undef,
  "integral concrete vanity sink combo" => undef,
  "the thickness of the diaphragm if the probe can measure 0-0.25mm" => undef,
  "the sum of two integers a and b, but you are not allowed to use the operator + and -." => undef,
  "derivative of tangent" => undef,
  "the force a 70.0-kg high jumper must exert on the ground to produce an upward acceleration 4.00 times the acceleration due to gravity." => undef,
  "date of fra for social secuirty" => undef,
  "cumulative probablility z-score" => undef,
  "the amount of heat (in kj) required to raise the temperature of a 79.0 g sample of ethanol from 298.0 k to 385.0 k. the specific heat capacity of ethanol is 2.42 j/g°c" => undef,
  "desmos secant line tangent derivative" => undef,
  "integral of inverse tangent" => undef,
  "cohen's d for t-test" => undef,
  "the ph of a solution containing an amphetamine concentration of 235 mg/l ." => undef,
  "derivative of natural log" => undef,
  "the temperature of the system once equilibrium + heat capacity" => undef,
  "solve. 2.7 b+5" => undef,
  "let c be the positively oriented circlex2+y2=1. use green's theorem to evaluate the line integral" => undef,
  "derivative of logarithmic functions" => undef,
  "integral almost square-free" => undef,
  "the force a 70.0-kg high jumper must exert on the ground to produce an upward acceleration 4.00 times the acceleration due to gravity. explicitly show how you follow the steps in the problem-solving strategy for newton's laws of motion." => undef,
  "why is dy/dx used to represent the derivative" => undef,
  "derivation of euler beam buckling formula for fixed-fixed column" => undef,
  "density chi-squared" => undef,
  "convex function second derivative" => undef,
  "security deposit deduction" => undef,
  "kp for the following reaction: h2(g) + co2(g) <=> h2o(g) + co(g); kc = 61 at 250 oc" => undef,
  "u''(f)+c u(f) = f" => undef,
  "second derivative" => undef,
  "derivative of trigometric functions cosine squared" => undef,
  "secondary ct ratio" => undef,
  "cohen's d for t-test formula" => undef,
  "social security withholding" => undef,
  "power +reflected by half-wavelength dipole" => undef,
  "for w in p = 2w + 2l, if p = 38 and l = 12." => undef,
  "length from sectional density" => undef,
  "the hydroxide ion concentration, [oh-], in 0.077 m hbr." => undef,
  "derivative of logarithm arbitrary base" => undef,
  "seconds to hours" => undef,
  "euclidea beta tangent" => undef,
  "integral of sin(x^2) 0 to inf" => undef,
  "integral of logarithm" => undef,
  "[v_a * t] = [v_b * t + 1/2a * t^2] for t" => undef,
  "derivative | define in a person/" => undef,
  "frequency sine" => undef,
  "derivative of sine proof" => undef,
  "your social security retirement benefit" => undef,
  "jboss7-reflections-vfs-integration-play2" => undef,
  "clementine 8tracks integration/" => undef,
  "cost of borrowing tmv" => undef,
  "url=http:/www.cdiscount.com/informatique/gaming/pack-thrustmaster-volant-t300-ferrari-integral-rac/f-0-0.html" => undef,
  "second numerical derivative" => undef,
  "integration of sin inverse" => undef,
  "cannot start under java 1.7.0_80-b15: java 1.8 or later is required. problem solve" => undef,
  "cost of charging phone" => undef,
  "fire eye security analytics integration" => undef,
  "security profile cisco vsg" => undef,
  "integral \\int \\left(x^2+ax-3\\right)^2dx" => undef,
  "derivative natural log" => undef,
  "missing letters pr-i-e-es-s" => undef,
  "ec2-54-173-116-203.compute-1.amazonaws.com:84423" => undef,
  "betterment funding-a-safety-net-calculate-your-target-amount" => undef,
  "\\wicked problem" => undef,
  "sine in sass" => undef,
  "devious devices - integration" => undef,
  "http:/qxmd.com/calculate/calculator_375/cll-ipi" => undef,
  "lim x-> -2, 2-|x|/2+x solve" => undef,
  "se for z-test in r without variance" => undef,
  "coulombs per second" => undef,
  "confidence interval in r lognormal distribution" => undef,
  "derivative of inverse tan" => undef,
  "ec2-52-6-28-224.compute-1" => undef,
  "z-score" => undef,
  "social security benefits" => undef,
  "date commandline +2h" => undef,
  "i=prt for t, if i=105, p=700, and r=0.05" => undef,
  "derivative of cos theta + phi" => undef,
  "tox setup.py integration+" => undef,
  "chainline for single speed" => undef,
  "the tangent sum formula derive" => undef,
  "added multi-nic support to gcloud alpha compute" => undef,
  "integrate e^-(x^2/a) dx from x=-∞ to ∞" => undef,
  "betterment.com goals-and-advice/funding-a-safety-net-calculate-your-target-amount" => undef,
  "assign cisco vsg security profile compute" => undef,
  "2,5 * 2,5" => undef,
  "find the tangent line of a derivative" => undef,
  "all t-stat simultaneously" => undef,
  "derivative of arc tan" => undef,
  "se for z-test in r unknown variance" => undef,
  "sinus in sass" => undef,
  "ecdh shared secret derivation" => undef,
  "natural log solve" => undef,
  "ec2-52-19-115-113.eu-west-1.compute.amazonaws.com" => undef,
  "derivative + investopedia" => undef,
  "derivative of logaryth" => undef,
  "the two-sided p value of the statistical test on paired samples x and y" => undef,
  "derivative of inverse tangent" => undef,
  "https:/mediendienst-integration.de/fileadmin/dateien/sarrazins_thesen_dossier.pdf" => undef,
  "deck cost" => undef,
  "cost of charging" => undef,
  "the maximum acceleration (in m/s2) of a car that is heading up a 12.5° slope (one that makes an angle of 12.5° with the horizontal) under th" => undef,
  "residuals/errors of a test model python" => undef,
  "for x ti-84" => undef,
  "f(x)=x^10 find the derivative" => undef,
  "package shipping cost" => undef,
  "derivative of constane*e^x" => undef,
  "localhost:ec2-54-173-219-50.compute-1.amazonaws.com" => undef,
  "mozilla-kde4-integration" => undef,
  "opportunity costs of production microeconomics" => undef,
  "compute-efficient geolocalization of targets from uav videos: real-time processing in unknown territory" => undef,
  "second order linear differential equation" => undef,
  "30,000 = what percentage of 160,000" => undef,
  "gas cost of driving somewhere" => undef,
  "ec2-54-158-143-248.compute-1.amazonaws.com :8890" => undef,
  "purpose.integration+valued+in+apple?" => undef,
  "euler-langrange derivation" => undef,
  "security profile" => undef,
  "calculate: 464*72" => undef,
  "66,4730 + (13,7516*65) + (5,0033*79) - (6,75550 * 34)" => undef,
  "z-scores in excel" => undef,
  "secon derivative" => undef,
  "cosinus integral" => undef,
  "does any bitcoin exchange besides btc-e offer metatrader integration" => undef,
  "integrate subtitles into mp4 mac -hardcode" => undef,
  "target/test-classes/fac-integration-test.properties" => undef,
  "\"added multi-nic support to gcloud alpha compute\"" => undef,
  "gupta-bleuler condition derivation" => undef,
  "absolute sign logarithm integral" => undef,
  "integration of 1-forms" => undef,
  "integrate bind to with /etc/hosts" => undef,
  "http:/developer.download.nvidia.com/compute/cuda/repos/ubuntu1404/x86_64 /" => undef,
  "+euclidea beta tangent" => undef,
  "fireeye security analytics integration" => undef,
  "derivative logarithm" => undef,
  "integral cse*da = sigma q" => undef,
  "calculate: 1500/30" => undef,
  "tangent line slope" => undef,
  "who is ec2-54-164-93-205.compute-1.amazonaws.com" => undef,
  "\\frac{d}{dx}\\left(\\frac{1}{\\sqrt{x}}\\right)\\:using\\:definition\\:of\\:derivative" => undef,
  "the van der waals parameter a of carbon dioxide from the values of the critical constants. +" => undef,
  "x-amazon-apigateway-integration" => undef,
  "nitrogen cross sections" => undef,
  "the equation (x+2)^3-2=0" => undef,
  "income elasticity of jam -.33" => undef,
  "integration of differental 1-forms" => undef,
  "integral curve (ϕ^(-ϕ) i ϕ)" => undef,
  "code-fibo phone country code not matching solve" => undef,
  "let cc be the positively oriented circle x2+y2=1x2+y2=1. use green's theorem to evaluate the line integral" => undef,
  "take-home pay" => undef,
  "solve.default system is computationally singular" => undef,
  "maxwell stress-energy tensor derivation" => undef,
  "ashes of the singularity asynchronous compute" => undef,
  "point of inflection second derivative" => undef,
  "integral ecology\\" => undef,
  "cost per square footage" => undef,
  "the cost of borrowing using time value" => undef,
  "challenges of it/ot integration" => undef,
  "system is computationally singular solve.default" => undef,
  "define business case for it/ot integration" => undef,
  "http:/www.ebay.de/itm/intel-compute-stick-stk1aw32sc-pc-system-schwarz-/381783846245?hash=item58e4172d65:g:axqaaosw8gvx6nzs" => undef,
  "ups shipping cost" => undef,
  "for w in p = 2w + 2l, if p = 38 and l = 12. w = a0" => undef,
  "ashes of the singularity syncronous compute" => undef,
  "derivative of log a over b" => undef,
  "power al-kashi algorithm" => undef,
  "\" the equation by completing the square. state whether the solutions are real or non-real.\"" => undef,
  "implicit second derivative" => undef,
  "integral of b dl over the path comprising a quarter section of a circle as shown" => undef,
  "normalized sinc antiderivative" => undef,
  "second numerical partial derivative" => undef,
  "solve-this-problem-iq-above-150 snopes.com" => undef,
  "each inequality for x. (a) 1 < ln(x) < 7" => undef,
  "secondary ct ration" => undef,
  "nitrogen cross sections labrilla" => undef,
  "0-60 speed from fps2" => undef,
  "gas cost" => undef,
  "pcrf-in integration" => undef,
  "http:/perennialmedicine.com/workshops/metal-integration-one-month-daily-reminders/" => undef,
  "residuals/errors method in python" => undef,
  "ec2-54-90-175-202.compute-1.amazonaws.com:admin" => undef,
  "cost savings system integration" => undef,
  "the molarity of the hydroxide ions in a solution that has been prepared by dissolving 51.2 g of barium hydroxide (ba(oh)2) in water and diluting the solution to a final volume of 4.00 l. (m.w's: ba 137.3 g/mol., o 16.0 g/mol, and h 1.0 g/mol)" => undef,
  "(17^-1) mod 101" => undef,
  "proust le cote de guermantes texte integral" => undef,
  "revenue and cost from a profit function" => undef,
  "differentiate natural log function" => undef,
  "boss7-reflections-vfs-integration-play2" => undef,
  "derive pa = lu factorization" => undef,
  "integrate cos^3 sin^2 from 0 to pi" => undef,
  "is there a one-to-one correspondence between branch points and poles of the derivative" => undef,
  "noip.com/integrate" => undef,
  "residuals/errors in python" => undef,
  "work/life integration" => undef,
  "integral for tangent" => undef,
  "define point of inflection second derivative" => undef,
  "ec2-50-112-51-207.us-west-2.compute.amazonaws.com" => undef,
  "http:/ec2-52-16-45-253.eu-west-1.compute.amazonaws.com/sites/ukdvsavideos/" => undef,
  "l for each subject using the contrast weights -1, 0, and 1." => undef,
  "inverse log calculate" => undef,
  "power reflected by half-wavelength dipole" => undef,
  "www.garantie-remboursement-integral;;.com" => undef,
  "borrowing cost of mortgage" => undef,
  "gnome-calendar-shell-integration" => undef,
  "integral product sin and cos" => undef,
  "66,4730 + (13,7516*65) + (5,0033*79) - (6,75550 * 34) * 1,2" => undef,
  "integration mit dem server-projekt" => undef,
  "p-solve" => undef,
  "i-compute.info" => undef,
  "lim_(x->(-2)^-) (2-abs(x))/(2+x) solve" => undef,
  "residuals/errors method" => undef,
  "the inverse a −1 mod n with fermat's theorem (if applicable) or eu- ler's theorem:" => undef,
  "integrate jquery data-animation" => undef,
  "power cost" => undef,
  "66,4730 + (13,7516*65) + (5,0033*79) - (6,75550 * 34) * 1,5" => undef,
  "www.i-compute.info" => undef,
  "finite difference second derivative" => undef,
  "derive inverse tangent" => undef,
  "rate mbps 32-bit float raw 96khz" => undef,
  "prove cscx derivative" => undef,
  "cost of commute" => undef,
  "integration mit dem backend-projekt" => undef,
  "missing webkit for firestorm or singularity viewers" => undef,
  "derivative of secant x" => undef,
  "integral natural log" => undef,
  "integrate 1/((1+x^2)*(1-2*a*x+x^2)) from x = -inf to x=inf" => undef,
  "tanh numpy derivative" => undef,
  "cory chase, molly jane - do you compute" => undef,
  "high-faluting derivation" => undef,
  "cassandra backup costs" => undef,
  "inverse tan derivative" => undef,
  "ec2-54-229-105-151.eu-west-1.compute.amazonaws.com" => undef,
  "artc sin derivative" => undef,
  "spring mvc + integration" => undef,
  "instructions per second" => undef,
  "integration mit dem server-anwendungssoftware" => undef,
  "ti-89 surface integral" => undef,
  "reverse+nullify>purpose.integration/pike" => undef,
  "cos using quadrants" => undef,
  "galletas caseras sin sal con harina integral" => undef,
  "calc/ package" => undef,
  "book_made_simple-entityreference-prepopulate-integration-for-og-2-1993694-1.patch" => undef,
  "the number of pounds of co2 released into the atmosphere when a 21.0-gallon tank of gasoline is burned in an automobile engine. assume that" => undef,
  "derivative cosine" => undef,
  "ip ec2-54-164-93-205.compute-1.amazonaws.com" => undef,
  "derivative securities, financial markets, and risk management" => undef,
  "http:/www.computerandyou.net/2012/01/how-to-solve-backspace-key-does-not-work-in-mozilla-firefox-in-ubuntu-linux/" => undef,
  "social security wages" => undef,
  "derivative of cosine with phase" => undef,
  "system is \"computationally singular\" solve.default" => undef,
  "cost of a house" => undef,
  "derivative of secant" => undef,
  "integrate inverse tan" => undef,
  "www.plussport.ch/fileadmin/integration/20141030 richtlinien hindernisfreie sportanlagen d.pdf" => undef,
  "derivative of logarythm" => undef,
  "https:/www.quora.com/how-do-you-solve-this-problem-without-trigonometry" => undef,
  "x to 3 power + 3x squared minus 5x -15" => undef,
  "integral of logarithm khan academy" => undef,
  "moving-google-integration-ungoogled-chromium/" => undef,
  "713 days after 3/31/16" => undef,
  "cost of charging device" => undef,
  "prove cotx derivative" => undef,
  "my social security benefits" => undef,
  "evaluating integral second derivative" => undef,
  "the check digit c for the 10-digit isbn codes below." => undef,
  "lim_(x->(-3)^-) (3-abs(x))/(3+x) solve" => undef,
  "derivative of sine from first principles" => undef,
  "average grocery cost" => undef,
  "derivative of sine" => undef,
  "http:/www.qxmd.com/apps/calculate-by-qxmd" => undef,
  "nitrogen ion mobility cross sections" => undef,
  "number of days since july 10" => undef,
  "30,000.00 = what percentage of 160,000.00" => undef,
  "natural log algebraically" => undef,
  "max-width based on screen size" => undef,
  "cumulative probably z-score" => undef,
  "cardflow+ integration" => undef,
  "ec2-52-19-115-113.eu-west-1.compute.amazonaws.com:" => undef,
  "deltag for the reaction pcl5 (g) +4h2 (g) > ph3 (g) +5hcl (g)" => undef,
  "differentiate s^2=x^2+y^2 for t" => undef,
  "ec2-176-34-155-23.eu-west-1.compute.amazonaws.com" => undef,
  "days since birth" => undef,
  "differentiate inverse sinus" => undef,
  "compute-efficient geolocalization of targets from uav videos: real-time processing in unknown territory .pdf" => undef,
  "order of a modulo n, for all possible a, for n = 19, 24 and 25. if you wish, you may write a simple program. for all cases, identify all primitive roots." => undef,
  "wget 'https:/nexus.opendaylight.org/content/repositories/opendaylight.snapshot/org/opendaylight/integration/distribution-karaf/0.3.0-snapshot/distribution-karaf-0.3.0-snapshot.zip" => undef,
  "hours minutes and seconds from seconds java" => undef,
  "mathematica draw tangent plot function derivative" => undef,
  "solve.defaultystem is computationally singular" => undef,
  "ec2-54-187-236-54.us-west-2.compute.amazonaws.com" => undef,
  "derivative of sin and cos" => undef,
  "power +reflected by antenna" => undef,
  "derivative-exposed banks" => undef,
  "gas cost for trip" => undef,
  "t-bills how to calculate" => undef,
  "sgi-solve" => undef,
  "nitrogen cross sections lebrilla" => undef,
  "random effects meta-analysis" => undef,
  "sin no calculator" => undef,
  "lognormal integral" => undef,
  "the radiation intensity at the receiving antenna half-length dipole" => undef,
  "programming c + integral" => undef,
  "single phase ac power" => undef,
  "integration of mean-variance model and stochastic indicator for portfolio optimization" => undef,
  "integration pc dans bureau*" => undef,
  "python c++ integration" => undef,
  "a integral c++" => undef,
  "derivative.h c++" => undef,
  "overflow c++" => undef,
  "derivative of a logarithm" => undef,
  "logarithms" => undef,
  "derivative lnx chain rule" => undef,
  "logarithmische integration" => undef,
  "integration test logging" => undef,
  "single phase ac poer" => undef,
  "integration-intranet\\.edf\\.fr:493" => undef,
  "logaritmes" => undef,
);
done_testing;
